export const MYDATA = [
  {
    id: 1,
    username: 'manjunathkalburgi',
    fullname: 'Manjunath Kalburgi',
    bio: 'Technical Architect building Saas projects and web apps.',
    dob: '30-07-1985',
    address:
      '#189,Manjunath Nilaya 3rd cross,Ravi nagar,Gokul road,Hubli-580030',
    pincode: 580030,
    mobile: 9986407307,
    email: 'manjunathkalburgi@gmail.com',
    education: [
      { id: 1, college: 'sksvmacet', address: 'laxmeshwara' },
      { id: 2, college: 'k.l.e polytechnic college,hubli' },
    ],
    experience: [
      { id: 1, company: 'bc forward' },
      { id: 2, company: 'quess' },
    ],
    hobbies: [
      { id: 1, hobby: 'dancing' },
      { id: 2, hobby: 'zumba' },
    ],
    projects: [
      {
        id: 1,
        title: 'project1',
        description: 'project1 description',
        start_date: '',
        end_date: '',
        tags: [
          'Front-end',
          'GPT-3',
          'Next.js',
          'React',
          'TailwindCSS',
          'Chrome Extension',
        ],
        demourl: 'https://yahoo.com',
        imageurl: 'https://picsum.photos/seed/picsum/200/300',
      },
      {
        id: 2,
        title: 'project2',
        description: 'project2 description',
        start_date: '',
        end_date: '',
        tags: [
          'Front-end',
          'GPT-3',
          'Next.js',
          'React',
          'TailwindCSS',
          'Chrome Extension',
        ],
        demourl: '',
        imageurl: 'https://picsum.photos/seed/picsum/200/300',
      },
      {
        id: 3,
        title: 'project3',
        description: 'project3 description',
        start_date: '',
        end_date: '',
        tags: [
          'Front-end',
          'GPT-3',
          'Next.js',
          'React',
          'TailwindCSS',
          'Chrome Extension',
        ],
        demourl: '',
        imageurl: 'https://picsum.photos/seed/picsum/200/300',
      },
    ],
  },
];
