export const RESOURCES = [
  {
    id: 1,
    title: 'stitches',
    description: 'description',
    link: 'https://stitches.dev/',
    rtype: 'utilities', //utilities/userinterface/everydayuse/freethemes/productivity
  },
  {
    id: 2,
    title: 'radix-ui',
    description: 'description',
    link: 'https://www.radix-ui.com/',
    rtype: 'userinterface',
  },
  {
    id: 3,
    title: 'bootstrap',
    description: 'description',
    link: 'https://www.bootstrap.com/',
    rtype: 'everydayuse',
  },
  {
    id: 4,
    title: 'bootstrap',
    description: 'description',
    link: 'https://www.freethemes.com/',
    rtype: 'freethemes',
  },
  {
    id: 4,
    title: 'productivity',
    description: 'description',
    link: 'https://www.productivity.com/',
    rtype: 'productivity',
  },
  {
    id: 4,
    title: 'productivity1',
    description: 'description1',
    link: 'https://www.productivity.com/',
    rtype: 'productivity',
  },
  {
    id: 5,
    title: 'reach ui',
    description: 'description1',
    link: 'https://reach.tech/',
    rtype: 'userinterface',
  },
  {
    id: 6,
    title: 'React Stately',
    description: 'description1',
    link: 'https://react-spectrum.adobe.com/index.html',
    rtype: 'userinterface',
  },
  {
    id: 7,
    title: 'reakit.io',
    description: 'description1',
    link: 'https://reakit.io/',
    rtype: 'userinterface',
  },
];
