export const SNIPPETS = [
  {
    id: 1,
    title: 'Navbar',
    description: 'description',
    liveurl: '/navbar',
    source: '',
    image: '',
  },
  {
    id: 2,
    title: 'Popover',
    description: 'description',
    liveurl: '/popover',
    source: '',
    image: '',
  },
  {
    id: 3,
    title: 'Toast',
    description: 'description',
    liveurl: '/toast',
    source: '',
    image: '',
  },
  {
    id: 4,
    title: 'demo',
    description: 'description',
    liveurl: '',
    source: '',
    image: '',
  },
  {
    id: 5,
    title: 'demo',
    description: 'description',
    liveurl: '',
    source: '',
    image: '',
  },
  {
    id: 6,
    title: 'demo',
    description: 'description',
    liveurl: '',
    source: '',
    image: '',
  },
  {
    id: 7,
    title: 'demo',
    description: 'description',
    liveurl: '',
    source: '',
    image: '',
  },
];
