export const SNIPPETS = [
  {
    id: 1,
    title: 'Menu',
    description: 'description',
    liveurl: '/menu',
    source: '',
    image: '',
  },
  {
    id: 1,
    title: 'Dropdown',
    description: 'description',
    liveurl: '/dropdown',
    source: '',
    image: '',
  },
  {
    id: 1,
    title: 'Toast',
    description: 'description',
    liveurl: '/toast',
    source: '',
    image: '',
  },
  {
    id: 1,
    title: 'demo',
    description: 'description',
    liveurl: '',
    source: '',
    image: '',
  },
  {
    id: 1,
    title: 'demo',
    description: 'description',
    liveurl: '',
    source: '',
    image: '',
  },
  {
    id: 1,
    title: 'demo',
    description: 'description',
    liveurl: '',
    source: '',
    image: '',
  },
  {
    id: 1,
    title: 'demo',
    description: 'description',
    liveurl: '',
    source: '',
    image: '',
  },
];
